// 🧭 Guided Competition Mode — 38 Master Steps across 13 Phases

export const PIPELINE_PHASES = [
  { id: 'PHASE_0', number: 0, titleEn: '🚀 Phase 0: Initialization', titleAr: '🚀 المرحلة 0: التهيئة والإعداد', color: '#00F0FF' },
  { id: 'PHASE_1', number: 1, titleEn: '🧠 Phase 1: Understand Before Coding', titleAr: '🧠 المرحلة 1: الفهم قبل البرمجة', color: '#7000FF' },
  { id: 'PHASE_2', number: 2, titleEn: '📊 Phase 2: Data Intelligence', titleAr: '📊 المرحلة 2: استخبارات البيانات', color: '#10B981' },
  { id: 'PHASE_3', number: 3, titleEn: '📐 Phase 3: Metric & Validation', titleAr: '📐 المرحلة 3: التقييم والتحقق', color: '#F59E0B' },
  { id: 'PHASE_4', number: 4, titleEn: '🚀 Phase 4: Baseline Pipeline', titleAr: '🚀 المرحلة 4: خط الأثر المرجعي Baseline', color: '#EC4899' },
  { id: 'PHASE_5', number: 5, titleEn: '🧩 Phase 5: Features & Alternatives', titleAr: '🧩 المرحلة 5: هندسة الميزات والنماذج البديلة', color: '#8B5CF6' },
  { id: 'PHASE_6', number: 6, titleEn: '🧪 Phase 6: Controlled Experimentation', titleAr: '🧪 المرحلة 6: التجارب المنضبطة', color: '#3B82F6' },
  { id: 'PHASE_7', number: 7, titleEn: '🔬 Phase 7: Deep Error Analysis', titleAr: '🔬 المرحلة 7: تحليل الأخطاء العميق', color: '#14B8A6' },
  { id: 'PHASE_8', number: 8, titleEn: '🧬 Phase 8: Model Diversity & Ensembling', titleAr: '🧬 المرحلة 8: تنوع النماذج والدمج', color: '#A855F7' },
  { id: 'PHASE_9', number: 9, titleEn: '📈 Phase 9: CV vs Leaderboard Control', titleAr: '📈 Phase 9: ضبط التوافق بين CV و LB', color: '#6366F1' },
  { id: 'PHASE_10', number: 10, titleEn: '🛡️ Phase 10: Final Red Team Audit', titleAr: '🛡️ المرحلة 10: التدقيق النهائي للفريق الأحمر', color: '#EF4444' },
  { id: 'PHASE_11', number: 11, titleEn: '🏆 Phase 11: Final Model Decision', titleAr: '🏆 المرحلة 11: اختيار النموذج النهائي', color: '#F59E0B' },
  { id: 'PHASE_12', number: 12, titleEn: '📤 Phase 12: Final Submission Pipeline', titleAr: '📤 المرحلة 12: خط التسليم النهائي', color: '#10B981' }
];

export const INITIAL_GUIDED_STEPS = [
  // --- PHASE 0 ---
  {
    id: 1,
    phase: 'PHASE_0',
    order: 1,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '📥 Collect All Competition Materials',
    titleAr: '📥 جمع كافة ملفات المسابقة',
    type: 'sequential', // sequential | parallel | review | blocking
    status: 'READY', // LOCKED | READY | IN_PROGRESS | REVIEW | DONE | BLOCKED
    dependsOn: [],
    unlocks: [2, 3, 4],
    guidanceEn: 'Before touching the models, collect everything. Download train.csv, test.csv, sample_submission, data dictionary, rules, and problem text.',
    guidanceAr: 'قبل البدء بإنشاء أي نموذج، اجمع كل الملفات. نزل بيانات التدريب، الاختبار، ملف التسليم العينة، ودليل البيانات.',
    aiTool: '🧠 ChatGPT / 💻 Codex',
    aiPrompt: 'List all files needed for a tabular Kaggle/IEEE ML competition and create a folder structure.',
    requiredOutput: 'All competition files downloaded & accessible.',
    handoffMessageEn: '🔔 Mohannad collected the competition materials. Dataset inspection & understanding can begin.',
    handoffMessageAr: '🔔 جمع مهند كافة ملفات المسابقة. يمكن البدء الآن بفحص البيانات والفهم.',
    recipient: 'all'
  },

  // --- PHASE 1 ---
  {
    id: 2,
    phase: 'PHASE_1',
    order: 2,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🧠 Understand Competition Objective & Metric',
    titleAr: '🧠 فهم هدف المسابقة ودالة التقييم',
    type: 'parallel',
    status: 'LOCKED',
    dependsOn: [1],
    unlocks: [5],
    guidanceEn: 'Paste the competition description into ChatGPT. Extract task type, metric direction, target column, and submission rules.',
    guidanceAr: 'انسخ وصف المسابقة إلى ChatGPT واستخرج نوع المهمة، اتجاه دالة التقييم، اسم العمود المستهدف، وقواعد التسليم.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: `Act as a senior Kaggle competition strategist. Read the competition description carefully. Do NOT suggest models yet. Extract: 1. Exact task type 2. What must be predicted 3. Target column 4. Evaluation metric 5. Whether higher or lower is better 6. Submission format 7. Important restrictions 8. Potential validation concerns 9. Potential leakage risks 10. Hidden details. Return a concise Competition Understanding Report.`,
    requiredOutput: 'Task Type, Target, Metric, Metric Direction, Restrictions.',
    handoffMessageEn: '🔔 Mohannad defined competition objective & evaluation metric.',
    handoffMessageAr: '🔔 أكمل مهند تحديد الهدف ودالة التقييم.',
    recipient: 'dyaa'
  },
  {
    id: 3,
    phase: 'PHASE_1',
    order: 3,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '📂 Dataset Structural Inspection',
    titleAr: '📂 فحص هيكلية ومكونات البيانات',
    type: 'parallel',
    status: 'LOCKED',
    dependsOn: [1],
    unlocks: [5],
    guidanceEn: 'Upload train.csv & test.csv to Gemini. Inspect shapes, missing values, column types, IDs, and candidate groups.',
    guidanceAr: 'ارفع train.csv و test.csv إلى Gemini. افحص أبعاد البيانات، القيم المفقودة، أنواع الأعمدة، والأعمدة المحتملة للمجموعات.',
    aiTool: '🔵 Gemini',
    aiPrompt: `You are the Data Intelligence Officer in an AI competition. Analyze train and test datasets. Inspect: shape, columns, dtypes, target, IDs, missing values, unique counts, categorical, numerical, suspicious columns, duplicates, group columns. Return a structured Dataset Structure Report.`,
    requiredOutput: 'Train/Test shapes, column dtypes, missing count, ID & target verified.',
    handoffMessageEn: '🔔 Moayad finished data structural inspection.',
    handoffMessageAr: '🔔 أنهى مؤيد الفحص الهيكلي للبيانات.',
    recipient: 'mohannad'
  },
  {
    id: 4,
    phase: 'PHASE_1',
    order: 4,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '📖 Independent Rules & Risk Review',
    titleAr: '📖 مراجعة مستقله للقواعد والمخاطر',
    type: 'parallel',
    status: 'LOCKED',
    dependsOn: [1],
    unlocks: [5],
    guidanceEn: 'Read rules independently from Mohannad & Moayad. Identify prohibited techniques, leakage traps, or ambiguous instructions.',
    guidanceAr: 'اقرأ شروط القواعد بشكل مستقل عن باقي الفريق. حدد التقنيات الممنوعة، فخاخ التسريب، والشروط الحاكمة.',
    aiTool: '🟠 Claude',
    aiPrompt: `Act as an independent competition reviewer. Read competition description & rules from scratch. Do not assume the team's interpretation is correct. Identify: exact objective, evaluation metric, submission rules, prohibited techniques, pretrained model rules, AI restrictions, runtime limits, submission limits, possible leakage traps. Return Independent Challenge Report.`,
    requiredOutput: 'Independent Challenge Report with risk alerts.',
    handoffMessageEn: '🔔 Dyaa finished independent rules & risk audit.',
    handoffMessageAr: '🔔 أنهى ضياء التقييم المستقل للمخاطر والقواعد.',
    recipient: 'mohannad'
  },
  {
    id: 5,
    phase: 'PHASE_1',
    order: 5,
    owner: 'both',
    ownerRole: '👑 Mohannad + 🛡️ Dyaa',
    titleEn: '⚖️ Challenge Understanding Review Gate',
    titleAr: '⚖️ بوابه مراجعة واعتماد تفاصيل المسابقة',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [2, 3, 4],
    unlocks: [6, 7, 8, 9],
    guidanceEn: 'Compare Mohannad report vs Dyaa report. If any conflict exists regarding target, metric, or rules, DO NOT unlock modeling until resolved.',
    guidanceAr: 'طابق تقرير مهند مع تقرير ضياء. إذا وجد أي اختلاف في الهدف أو دالة التقييم، لا تفتح مرحلة النماذج حتى يتم حسم الخلاف.',
    aiTool: '🧠 ChatGPT / 🟠 Claude',
    aiPrompt: 'Compare the two independent competition reports. List all matching points and highlight any discrepancies in metric, target definition, or data split.',
    requiredOutput: 'Signed Competition Definition Agreement.',
    handoffMessageEn: '🟢 Competition objective, rules, target and metric are confirmed by Red Team. Data analysis can proceed.',
    handoffMessageAr: '🟢 تم اعتماد الهدف ودالة التقييم من الفريق الأحمر. يمكن البدء بتحليل البيانات المتقدم.',
    recipient: 'all'
  },

  // --- PHASE 2 ---
  {
    id: 6,
    phase: 'PHASE_2',
    order: 6,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '🧹 Data Quality Analysis',
    titleAr: '🧹 تحليل جودة البيانات وتنظيفها',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [5],
    unlocks: [7],
    guidanceEn: 'Inspect missing value percentages, duplicate rows/IDs, constant columns, infinite values, and extreme outliers.',
    guidanceAr: 'افحص نسب القيم المفقودة، الصفوف المكررة، الأعمدة الثابتة، والقيم الشاذة.',
    aiTool: '🔵 Gemini + 💻 Codex',
    aiPrompt: `Write a Python pandas data quality script to check: missing %, dup rows, dup IDs, constant columns, infinite values, extreme quantiles, and data type mismatches on train and test.`,
    requiredOutput: 'Data Quality Report with clean data recommendations.',
    handoffMessageEn: '🔔 Moayad finished data quality audit.',
    handoffMessageAr: '🔔 أنهى مؤيد تدقيق جودة البيانات.',
    recipient: 'mohannad'
  },
  {
    id: 7,
    phase: 'PHASE_2',
    order: 7,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '🎯 Target Distribution Analysis',
    titleAr: '🎯 تحليل توزيع المتغير المستهدف Target',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [6],
    unlocks: [8, 10],
    guidanceEn: 'Analyze target distribution: class imbalance for classification, skewness/log1p for regression, temporal trends for time series.',
    guidanceAr: 'حلل توزيع الهدف: توازن الفئات في التصنيف، الالتواء للإنحدار، والنمط الزمني للسلاسل الزمنية.',
    aiTool: '🔵 Gemini',
    aiPrompt: `Analyze the target column distribution. Check class balance, skewness, zero-inflation, log1p transformation benefits, and temporal consistency. Output Target Analysis Report.`,
    requiredOutput: 'Target Analysis Report.',
    handoffMessageEn: '🔔 Moayad completed target analysis. Mohannad can refine local validation strategy.',
    handoffMessageAr: '🔔 أكمل مؤيد تحليل الهدف. يمكن لمهند إعداد استراتيجية التقييم الآن.',
    recipient: 'mohannad'
  },
  {
    id: 8,
    phase: 'PHASE_2',
    order: 8,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '🚨 Leakage Investigation',
    titleAr: '🚨 التحقيق في تسريب البيانات Leakage',
    type: 'blocking',
    status: 'LOCKED',
    dependsOn: [5],
    unlocks: [9],
    guidanceEn: 'Try to break the competition! Check for target-derived features, ID timestamp ordering, future info, or train/test duplicates.',
    guidanceAr: 'حاول كسر المسابقة! ابحث عن الميزات المحشوة بالهدف، ترتيب المعرفات الزمني، المعومات المستقبلية، أو التكرار بين التدريب والاختبار.',
    aiTool: '🔵 Gemini + 🟠 Claude',
    aiPrompt: `Scan dataset columns for potential target leakage: columns with high correlation with target (>0.98), ID sequence correlation, post-event features, train/test exact row overlaps.`,
    requiredOutput: 'Leakage Audit Result (🟢 None, 🟡 Possible, 🔴 Critical).',
    handoffMessageEn: '🔔 Moayad finished leakage investigation.',
    handoffMessageAr: '🔔 أنهى مؤيد التحقيق في تسريب البيانات.',
    recipient: 'dyaa'
  },
  {
    id: 9,
    phase: 'PHASE_2',
    order: 9,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '🔀 Train vs Test Distribution Shift Analysis',
    titleAr: '🔀 فحص انزياح البيانات بين التدريب والاختبار',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [8],
    unlocks: [12],
    guidanceEn: 'Compare train and test feature distributions. Optionally run Adversarial Validation (classifier separating train vs test).',
    guidanceAr: 'ارسم وقارن توزيع الميزات بين التدريب والاختبار. اختبر Adversarial Validation بربط الصفوف بالتدريب أو الاختبار.',
    aiTool: '🔵 Gemini + 💻 Codex',
    aiPrompt: `Write Python code to compute Kolmogorov-Smirnov distance between train and test features, and build an Adversarial Validation classifier (AUC > 0.70 means shift).`,
    requiredOutput: 'Train/Test Shift Report.',
    handoffMessageEn: '🔔 Moayad completed Train/Test Shift analysis.',
    handoffMessageAr: '🔔 أكمل مؤيد تحليل انزياح البيانات.',
    recipient: 'mohannad'
  },

  // --- PHASE 3 ---
  {
    id: 10,
    phase: 'PHASE_3',
    order: 10,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '📐 Implement Local Competition Metric',
    titleAr: '📐 برمجة دالة التقييم المحلية Exact Metric',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [7],
    unlocks: [11],
    guidanceEn: 'Write exact local Python implementation of the evaluation metric. Test with sample arrays and edge cases.',
    guidanceAr: 'اكتب كود دالة التقييم بالبايثون محلياً. اختبر الكود بقيم افتراضية لضمان الدقة وتحديد الاتجاه.',
    aiTool: '🧠 ChatGPT / 💻 Codex',
    aiPrompt: `Write a scikit-learn compatible custom metric function for [insert metric name]. Ensure correct handling of probabilities, thresholds, edge cases, and average parameter.`,
    requiredOutput: 'Verified Local Metric Python Function.',
    handoffMessageEn: '🔔 Mohannad implemented local metric. Dyaa must verify independently.',
    handoffMessageAr: '🔔 برمّج مهند دالة التقييم المحلية. يجب على ضياء مراجعتها واختبارها.',
    recipient: 'dyaa'
  },
  {
    id: 11,
    phase: 'PHASE_3',
    order: 11,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🧪 Independently Verify Metric Implementation',
    titleAr: '🧪 مراجعة دالة التقييم محلياً بشكل مستقل',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [10],
    unlocks: [12],
    guidanceEn: 'Reimplement or unit-test Mohannad metric function. Check clipping, log transform, zero-division, and average parameters.',
    guidanceAr: 'أعد كتابة دالة التقييم بشكل مستقل أو اختبرها بوحدات اختبار Unit Test للتأكد من عدم وجود أخطاء حسابية.',
    aiTool: '🟠 Claude / 🔢 DeepSeek',
    aiPrompt: `Review this custom metric code for mathematical errors, clipping bugs, or wrong threshold logic. Compare against official metric definition.`,
    requiredOutput: 'Metric Clearance Approval.',
    handoffMessageEn: '✅ Dyaa verified local metric implementation.',
    handoffMessageAr: '✅ وافق ضياء على دالة التقييم المحلية.',
    recipient: 'mohannad'
  },
  {
    id: 12,
    phase: 'PHASE_3',
    order: 12,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🎯 Formulate Validation Strategy (KFold/Group/Time)',
    titleAr: '🎯 تحديد استراتيجية التقييم التقاطعي Validation',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [9, 11],
    unlocks: [13],
    guidanceEn: 'Select split strategy based on data structure: StratifiedKFold (classification), GroupKFold (grouped entities), TimeSeriesSplit (chronological).',
    guidanceAr: 'اختر نوع التجزئة بناء على هيكل البيانات: StratifiedKFold للتصنيف، GroupKFold للمجموعات، أو TimeSeriesSplit للوقت.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: `Based on data structure (groups: [YES/NO], time-series: [YES/NO], imbalance: [YES/NO]), recommend exact scikit-learn cross-validation splitter and seed setup.`,
    requiredOutput: 'Validation Strategy Blueprint (folds, split type, seed).',
    handoffMessageEn: '🔔 Mohannad formulated validation strategy. Dyaa must attack validation strategy.',
    handoffMessageAr: '🔔 حدد مهند استراتيجية التقييم. يجب على ضياء فحصها واختبار ثغراتها.',
    recipient: 'dyaa'
  },
  {
    id: 13,
    phase: 'PHASE_3',
    order: 13,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🛡️ Attack Validation Strategy',
    titleAr: '🛡️ فحص ثغرات استراتيجية التقييم Red Team Attack',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [12],
    unlocks: [14],
    guidanceEn: 'Attempt to break Mohannad validation scheme: check for group leakage, temporal leakage, duplicate leakage, or fold target shift.',
    guidanceAr: 'هاجم مخطط التقييم المحتسب: ابحث عن تسريب المجموعات، التسريب الزمني، التكرار بين الطيات، أو انحراف الهدف.',
    aiTool: '🟠 Claude / ⚡ Antigravity',
    aiPrompt: `Critique this cross-validation strategy: StratifiedGroupKFold(n_splits=5). Check for hidden temporal leakage, repeated entities across folds, or data contamination.`,
    requiredOutput: 'Validation Approval or Rejection Decision.',
    handoffMessageEn: '🟢 Validation strategy approved by Red Team. Baseline modeling is unlocked.',
    handoffMessageAr: '🟢 تمت الموافقة على استراتيجية التقييم من الفريق الأحمر. تم فتح مرحلة النماذج المرجعية.',
    recipient: 'all'
  },

  // --- PHASE 4 ---
  {
    id: 14,
    phase: 'PHASE_4',
    order: 14,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '⚙️ Build Simplest Valid End-to-End Baseline',
    titleAr: '⚙️ بناء أول نموذج مرجعي بسيط End-to-End Baseline',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [13],
    unlocks: [15],
    guidanceEn: 'Train simplest CatBoost / LightGBM baseline on 5 folds. Verify pipeline loads data, fits folds, records OOF, and calculates CV score.',
    guidanceAr: 'أنشئ أبسط نموذج مرجعي (CatBoost أو LightGBM) عبر 5 طيات. تأكد أن الأنبوب يحمل البيانات، يدرب الطيات، ويحسب CV.',
    aiTool: '🧠 ChatGPT / 💻 Codex',
    aiPrompt: `Write clean 5-Fold StratifiedKFold baseline script using CatBoost/LightGBM. Calculate OOF predictions, output exact local metric score, and return test predictions array.`,
    requiredOutput: 'Baseline Code, Baseline CV Score & OOF Array.',
    handoffMessageEn: '🔔 Mohannad built baseline model. Dyaa must audit baseline code.',
    handoffMessageAr: '🔔 بنى مهند النموذج المرجعي الأول. يجب على ضياء فحص الكود.',
    recipient: 'dyaa'
  },
  {
    id: 15,
    phase: 'PHASE_4',
    order: 15,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🐞 Baseline Code & Pipeline QA',
    titleAr: '🐞 التدقيق البرمجي لأنبوب النموذج المرجعي',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [14],
    unlocks: [16],
    guidanceEn: 'Inspect baseline script for preprocessor leakage (fit outside fold), wrong index alignment, missing inverse transform, or target leakage.',
    guidanceAr: 'افحص كود النموذج المرجعي للتأكد من تنفيذ التجهيز داخل كل طية (Inside-Fold Fit)، ومطابقة الفهارس وشكل التوقعات.',
    aiTool: '🟠 Claude / 💻 Codex',
    aiPrompt: `Perform code QA on this ML pipeline script: check for target encoding leakage outside folds, scaler fit on whole train, indexing bugs, NaN prediction outputs.`,
    requiredOutput: 'Baseline Code QA Clearance.',
    handoffMessageEn: '🛡️ Dyaa cleared baseline code pipeline.',
    handoffMessageAr: '🛡️ اعتقد ضياء أنبوب النموذج المرجعي.',
    recipient: 'mohannad'
  },
  {
    id: 16,
    phase: 'PHASE_4',
    order: 16,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '📤 Generate First Submission File EARLY',
    titleAr: '📤 إنشاء أول ملف تسليم واختبار التنسيق',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [15],
    unlocks: [17],
    guidanceEn: 'Generate submission_baseline.csv. Verify row count, column names, ID alignment, prediction bounds, and absence of NaNs.',
    guidanceAr: 'أنشئ ملف التسليم الأول submission_baseline.csv. افحص عدد الصفوف، أسماء الأعمدة، عدم وجود NaN، والقيم المعقولة.',
    aiTool: '💻 Codex',
    aiPrompt: `Write Python code to format OOF test predictions into sample_submission.csv schema. Verify exact row count, non-null values, correct column header names.`,
    requiredOutput: 'submission_baseline.csv generated.',
    handoffMessageEn: '🔔 Mohannad generated baseline submission file. Dyaa must validate submission schema.',
    handoffMessageAr: '🔔 أنشأ مهند ملف التسليم المرجعي الأول. يجب على ضياء فحصه.',
    recipient: 'dyaa'
  },
  {
    id: 17,
    phase: 'PHASE_4',
    order: 17,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🛡️ Baseline Submission File Schema QA',
    titleAr: '🛡️ فحص مطابقة وتكامل ملف التسليم المرجعي',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [16],
    unlocks: [18],
    guidanceEn: 'Compare submission_baseline.csv against sample_submission.csv. Confirm matching row count, exact IDs order, and prediction formatting.',
    guidanceAr: 'طابق ملف التسليم المرجعي مع ملف العينة sample_submission.csv. تأكد من تطابق الصفوف، الترتيب، والأسماء.',
    aiTool: '🟠 Claude / 💻 Codex',
    aiPrompt: `Verify two submission CSV files in Python: check row count equality, ID column alignment, column names match, no NaNs or Infs present.`,
    requiredOutput: 'Submission Schema QA Clearance.',
    handoffMessageEn: '🛡️ Dyaa approved baseline submission file. Safe to upload to Kaggle/IEEE.',
    handoffMessageAr: '🛡️ اعترف ضياء بسلامة ملف التسليم. جاهز للرفع على المنصة.',
    recipient: 'mohannad'
  },
  {
    id: 18,
    phase: 'PHASE_4',
    order: 18,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🌐 Upload First Baseline Submission to Leaderboard',
    titleAr: '🌐 رفع أول تسليم مرجعي على لوحة الصدارة',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [17],
    unlocks: [19, 20],
    guidanceEn: 'Upload submission_baseline.csv to platform. Record Public LB score in Experiment Table & score tracker.',
    guidanceAr: 'ارفع ملف التسليم المرجعي على المنصة. سجل نتيجة لوحة الصدارة العامة Public LB في جدول التجارب.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Record baseline submission LB score, compute CV vs LB gap, and evaluate validation pipeline stability.',
    requiredOutput: 'EXP-001 Logged with CV & Public LB scores.',
    handoffMessageEn: '🎉 END-TO-END PIPELINE VERIFIED! Baseline submission recorded successfully.',
    handoffMessageAr: '🎉 تم فحص واختبار خط الأثر بالكامل بنجاح! تم تسجيل النتيجة المرجعية الأولى.',
    recipient: 'all'
  },

  // --- PHASE 5 ---
  {
    id: 19,
    phase: 'PHASE_5',
    order: 19,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '🧩 Generate Feature Engineering Hypotheses',
    titleAr: '🧩 صياغة فرضيات هندسة الميزات المتقدمة',
    type: 'parallel',
    status: 'LOCKED',
    dependsOn: [18],
    unlocks: [20],
    guidanceEn: 'Propose structured feature ideas: interaction ratios, group aggregations, log transforms, frequency encoding, time deltas.',
    guidanceAr: 'اقترح ميزات جديدة: نسب التفاعل، التجميعات الإحصائية حسب المجموعات، التحويلات اللوجاريتمية، وتردد الفئات.',
    aiTool: '🔵 Gemini',
    aiPrompt: `Generate 10 domain-specific feature engineering hypotheses for tabular ML data. Include feature name, mathematical formula, hypothesis reason, and potential leakage risk.`,
    requiredOutput: 'Feature Engineering Hypotheses List.',
    handoffMessageEn: '📊 Moayad prepared new feature hypotheses for testing.',
    handoffMessageAr: '📊 أعد مؤيد قائمة الفرضيات والميزات الجديدة للتجربة.',
    recipient: 'mohannad'
  },
  {
    id: 20,
    phase: 'PHASE_5',
    order: 20,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🧪 Build Independent Alternative Model Branch',
    titleAr: '🧪 بناء فرع نماذج بديل مستقل (Alternative Branch)',
    type: 'parallel',
    status: 'LOCKED',
    dependsOn: [18],
    unlocks: [21],
    guidanceEn: 'Build an independent alternative modeling pipeline (e.g. XGBoost or ExtraTrees) using different feature preprocessing.',
    guidanceAr: 'ابن خوارزمية نموذج مستقلة بديلة (مثل XGBoost أو ExtraTrees) باستخدام تجهيز ميزات مختلف لضمان التنوع.',
    aiTool: '🟠 Claude / 🔢 DeepSeek',
    aiPrompt: `Write an independent XGBoost / ExtraTrees 5-Fold cross-validation script. Record local CV score and store OOF predictions array.`,
    requiredOutput: 'Alternative Model Branch Tested with OOF Predictions.',
    handoffMessageEn: '🛡️ Dyaa tested alternative model architecture.',
    handoffMessageAr: '🛡️ اختبر ضياء نموذجاً بديل استقلالي لدمج التوقعات.',
    recipient: 'mohannad'
  },

  // --- PHASE 6 ---
  {
    id: 21,
    phase: 'PHASE_6',
    order: 21,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🧪 Populate & Prioritize Controlled Experiment Queue',
    titleAr: '🧪 ترتيب أولوية قائمة التجارب المنضبطة',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [19, 20],
    unlocks: [22],
    guidanceEn: 'Combine Moayad feature ideas + Dyaa alternative models + Mohannad ideas into ranked experiment queue (EXP-002, EXP-003, etc.).',
    guidanceAr: 'دمج مقترحات مؤيد وضياء مع أفكار مهند وترتيب أولوية التجارب القادمة (EXP-002, EXP-003...).',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Create a prioritized ML experiment backlog matrix containing Experiment ID, Hypothesis, Owner, Feature Set, Model, Priority.',
    requiredOutput: 'Prioritized Experiment Queue.',
    handoffMessageEn: '🔔 Mohannad populated experiment queue.',
    handoffMessageAr: '🔔 أعد مهند جدول أولوية التجارب.',
    recipient: 'all'
  },
  {
    id: 22,
    phase: 'PHASE_6',
    order: 22,
    owner: 'mohannad',
    ownerRole: '👑 Active Experiment Owner',
    titleEn: '⚠️ Run Controlled Experiment (One Major Change at a Time)',
    titleAr: '⚠️ تنفيذ تجربة منضبطة (تغيير رئيسي واحد في كل مرة)',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [21],
    unlocks: [23],
    guidanceEn: 'GOLDEN RULE: Change only ONE major component per experiment. Record CV score before & after to isolate exact gain.',
    guidanceAr: 'القاعدة الذهبية: غير عنصراً رئيسياً واحداً فقط في كل تجربة. سجل نتيجة CV قبل وبعد لعزل الفائدة بدقة.',
    aiTool: '💻 Codex / 🧠 ChatGPT',
    aiPrompt: 'Execute single-variable ML experiment, compute 5-fold CV score delta, and check CV standard deviation change.',
    requiredOutput: 'Experiment Logged with Delta CV.',
    handoffMessageEn: '🔔 Controlled experiment completed.',
    handoffMessageAr: '🔔 اكتملت التجربة المنضبطة.',
    recipient: 'mohannad'
  },
  {
    id: 23,
    phase: 'PHASE_6',
    order: 23,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '⚖️ Interpret Experiment Decision (Keep / Drop / Investigate)',
    titleAr: '⚖️ اتخاذ القرار بشأن التجربة (إبقاء / إلغاء / تحقيق)',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [22],
    unlocks: [24, 26],
    guidanceEn: 'KEEP if CV improves consistently. DROP if CV worsens. INVESTIGATE if mean CV improves but variance explodes or LB contradicts CV.',
    guidanceAr: 'اعتمِد التجارب التي ترفع CV بثبات. التغِ ما يخفض النتيجة. وافحص التجربة إذا ارتفع CV بشكل شاذ.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Evaluate experiment CV delta. If CV improvement > 0.001 and CV std is stable, approve KEEP. Otherwise decision DROP.',
    requiredOutput: 'Experiment Decision Logged (KEEP/DROP).',
    handoffMessageEn: '🔔 Mohannad logged experiment decision.',
    handoffMessageAr: '🔔 اتخذ مهند قرار التجربة الحالي.',
    recipient: 'all'
  },

  // --- PHASE 7 ---
  {
    id: 24,
    phase: 'PHASE_7',
    order: 24,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '🔍 Error Segment & Residual Analysis',
    titleAr: '🔍 تحليل القطاعات الأكثر خطأً (Error Segments)',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [23],
    unlocks: [25],
    guidanceEn: 'Analyze samples with worst predictions/residuals. Identify whether specific categories, numeric ranges, or classes suffer high error.',
    guidanceAr: 'حلل العينات التي حقق فيها النموذج أعلى نسبة خطأ. حدد الفئات أو المجموعات المتضررة.',
    aiTool: '🔵 Gemini + 💻 Codex',
    aiPrompt: `Write Python script to filter top 5% highest absolute prediction error rows. Slice error distribution across key categorical and numerical features.`,
    requiredOutput: 'Worst-Performing Segments Report.',
    handoffMessageEn: '📊 Moayad completed error segment analysis.',
    handoffMessageAr: '📊 أنهى مؤيد تحليل قطاعات الخطأ.',
    recipient: 'mohannad'
  },
  {
    id: 25,
    phase: 'PHASE_7',
    order: 25,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🎯 Targeted Improvement Experiment',
    titleAr: '🎯 إطلاق تجربة مستهدفة لـ علاج نقاط الضعف',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [24],
    unlocks: [26],
    guidanceEn: 'Use Moayad error segment report to build targeted features/sample weights targeting model weaknesses.',
    guidanceAr: 'استخدم تقرير خطأ القطاعات لإنشاء ميزات خاصة معالجة لنقاط ضعف النموذج بدلاً من التعقيد العشوائي.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Design targeted feature engineering strategy specifically focused on improving model performance on worst-performing data segments.',
    requiredOutput: 'Targeted Experiment Evaluated.',
    handoffMessageEn: '🔔 Mohannad completed targeted improvement experiment.',
    handoffMessageAr: '🔔 أنهى مهند التجربة المستهدفة لمعالجة الأخطاء.',
    recipient: 'mohannad'
  },

  // --- PHASE 8 ---
  {
    id: 26,
    phase: 'PHASE_8',
    order: 26,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🏅 Select Strong Candidate Models for Ensembling',
    titleAr: '🏅 اختيار النماذج المرشحة للدمج Ensemble',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [23, 25],
    unlocks: [27],
    guidanceEn: 'Select top 2-4 distinct models based primarily on local CV stability and low fold variance (CatBoost, LightGBM, XGBoost, NN).',
    guidanceAr: 'اختر 2-4 نماذج قوية ومختلفة بناءً على ثبات التقييم المحلي وحيود الطيات المخفض.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Select candidate models for ensembling based on local CV score, cross-fold standard deviation, and architectural diversity.',
    requiredOutput: 'Ensemble Candidates Selected (Candidate A, B, C).',
    handoffMessageEn: '🔔 Mohannad selected candidate models for ensembling.',
    handoffMessageAr: '🔔 حدد مهند النماذج المرشحة للدمج.',
    recipient: 'dyaa'
  },
  {
    id: 27,
    phase: 'PHASE_8',
    order: 27,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🔍 Verify Model Diversity & OOF Correlation',
    titleAr: '🔍 فحص التنوع والارتباط بين توقعات النماذج OOF',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [26],
    unlocks: [28],
    guidanceEn: 'Compute pairwise Pearson/Spearman correlation matrix of candidate model OOF predictions. Ensure correlation < 0.90 for ensemble gain.',
    guidanceAr: 'احسب مصفوفة الارتباط بين توقعات النماذج المرشحة. تأكد أن نسبة الارتباط أقل من 0.90 لضمان الحصول على فائدة حقيقية.',
    aiTool: '🟠 Claude / 💻 Codex',
    aiPrompt: `Write Python snippet to compute pairwise correlation matrix of OOF prediction vectors. Flag model pairs with correlation > 0.95.`,
    requiredOutput: 'Model Diversity Audit Report.',
    handoffMessageEn: '🛡️ Dyaa verified model diversity for ensembling.',
    handoffMessageAr: '🛡️ فحص ضياء التنوع واعترف بصحة النماذج المرشحة للدمج.',
    recipient: 'mohannad'
  },
  {
    id: 28,
    phase: 'PHASE_8',
    order: 28,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🧬 Evaluate Blending & Rank Averaging Ensembles',
    titleAr: '🧬 تقييم ودمج التوقعات (Blending & Rank Averaging)',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [27],
    unlocks: [29],
    guidanceEn: 'Test weighted averaging, Nelder-Mead OOF optimization, or rank blending. Evaluate ensemble score strictly on local OOF CV.',
    guidanceAr: 'اختبر الدمج الموزون، التحسين الرياضي Nelder-Mead، أو متوسط الرتب. قَيّم النتيجة حصرياً على OOF CV المحتسب.',
    aiTool: '🧠 ChatGPT / 💻 Codex',
    aiPrompt: `Write scipy.optimize Nelder-Mead blending optimizer to find optimal weights maximizing local CV macro F1 score on OOF prediction matrix.`,
    requiredOutput: 'Ensemble Evaluated with OOF CV Gain.',
    handoffMessageEn: '🔔 Mohannad evaluated ensemble performance.',
    handoffMessageAr: '🔔 أنهى مهند تقييم وتوليد ناتج دمج النماذج.',
    recipient: 'mohannad'
  },

  // --- PHASE 9 ---
  {
    id: 29,
    phase: 'PHASE_9',
    order: 29,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '📊 Compare Local CV vs Public Leaderboard Matrix',
    titleAr: '📊 مقارنة تقييم CV المحلي مع لوحة الصدارة LB',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [28],
    unlocks: [30, 31, 32],
    guidanceEn: 'Build CV vs LB tracking matrix. Check for Leaderboard Overfitting (CV drops but LB improves) vs True Progression (CV & LB both improve).',
    guidanceAr: 'أنشئ مصفوفة تتبع الفروق بين CV و LB. حذارِ من فرط التوافق على لوحة الصدارة (انخفاض CV وارتفاع LB بشكل وهمي).',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Analyze historical CV vs Public LB score progression table. Flag overfitting risks, rank stability, and recommend trust strategy.',
    requiredOutput: 'Score Relationship & Overfitting Assessment.',
    handoffMessageEn: '🔔 Mohannad completed CV vs Public LB relationship review.',
    handoffMessageAr: '🔔 استعرض مهند العلاقة بين التقييم المحلي ولوحة الصدارة.',
    recipient: 'dyaa'
  },

  // --- PHASE 10 ---
  {
    id: 30,
    phase: 'PHASE_10',
    order: 30,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🚨 Final Leakage Audit on Chosen Pipeline',
    titleAr: '🚨 التدقيق النهائي الحاسم لتسريب البيانات (Final Leakage)',
    type: 'blocking',
    status: 'LOCKED',
    dependsOn: [29],
    unlocks: [33],
    guidanceEn: 'Perform rigorous re-check of target leakage, time leakage, group contamination, or global preprocessor fitting on final candidate pipeline.',
    guidanceAr: 'أعد فحص التدقيق الحاسم للتسريب في الأنبوب النهائي قبل فتح مرحلة الاعتماد.',
    aiTool: '🟠 Claude / ⚡ Antigravity',
    aiPrompt: `Perform exhaustive final leakage audit on final ensemble pipeline code. Verify zero target leakage, fold independence, and test isolation.`,
    requiredOutput: 'Final Leakage Audit Clearance Decision.',
    handoffMessageEn: '🛡️ Dyaa completed final leakage audit.',
    handoffMessageAr: '🛡️ أكمل ضياء التدقيق النهائي للتسريب.',
    recipient: 'mohannad'
  },
  {
    id: 31,
    phase: 'PHASE_10',
    order: 31,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🐞 Final Code & Reproducibility Audit',
    titleAr: '🐞 التدقيق البرمجي النهائي وإعادة الإنتاج (Reproducibility)',
    type: 'blocking',
    status: 'LOCKED',
    dependsOn: [29],
    unlocks: [33],
    guidanceEn: 'Audit inference script reproducibility, seed setting, exact file paths, model weight saves, and deterministic prediction output.',
    guidanceAr: 'تدقيق إعادة إنتاج الكود، تصفير البذور العشوائية Random Seeds، ومسارات الحفظ لضمان نفس النتيجة بدقة.',
    aiTool: '🟠 Claude',
    aiPrompt: `Review final inference script for seed consistency, model weights loading, missing inverse scaling, and prediction order determinism.`,
    requiredOutput: 'Final Code Audit Clearance.',
    handoffMessageEn: '🛡️ Dyaa passed final code & reproducibility audit.',
    handoffMessageAr: '🛡️ وافق ضياء على سلامة الكود النهائي وموثوقية إنتاجه.',
    recipient: 'mohannad'
  },
  {
    id: 32,
    phase: 'PHASE_10',
    order: 32,
    owner: 'moayad',
    ownerRole: '📊 Moayad (Data Intelligence)',
    titleEn: '📊 Final Data Pipeline Verification',
    titleAr: '📊 التثبت النهائي من أنبوب تحويل البيانات',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [29],
    unlocks: [33],
    guidanceEn: 'Verify exact feature transformation alignment between train and test datasets, column ordering, category mapping, and missing imputation.',
    guidanceAr: 'تأكد من تطابق معالجة ومصفوفات البيانات بين التدريب والاختبار، وترتيب الأعمدة المعالجة.',
    aiTool: '🔵 Gemini',
    aiPrompt: `Verify train and test feature matrices: check exact column order match, identical categorical dtypes, and no missing feature columns.`,
    requiredOutput: 'Final Data Pipeline Verification Clearance.',
    handoffMessageEn: '📊 Moayad verified final data pipeline consistency.',
    handoffMessageAr: '📊 أقر مؤيد بتطابق أنبوب معالجة البيانات بين التدريب والاختبار.',
    recipient: 'mohannad'
  },

  // --- PHASE 11 ---
  {
    id: 33,
    phase: 'PHASE_11',
    order: 33,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '👑 Select Final Candidate Submission Model',
    titleAr: '👑 اختيار النموذج والملف المرشح للتسليم النهائي',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [30, 31, 32],
    unlocks: [34],
    guidanceEn: 'Select final submission candidate based on best validated local CV, fold stability, and Red Team clearance.',
    guidanceAr: 'اختر النموذج النهائي للتسليم بناءً على أفضل CV محلي محتسب، ثبات التقييم، واعتماد الفريق الأحمر.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Synthesize top ensemble vs single model choices. Recommend safest final candidate selection balancing CV score and fold stability.',
    requiredOutput: 'Final Candidate Model Selected.',
    handoffMessageEn: '🔔 Mohannad selected final candidate model.',
    handoffMessageAr: '🔔 حدد مهند النموذج النهائي المرشح.',
    recipient: 'all'
  },
  {
    id: 34,
    phase: 'PHASE_11',
    order: 34,
    owner: 'mohannad',
    ownerRole: '🤖 Aura AI + 👑 Mohannad',
    titleEn: '🧠 Final Decision Telemetry Analysis',
    titleAr: '🧠 التحليل الآلي واستشاره الذكاء الاصطناعي للقرار النهائي',
    type: 'review',
    status: 'LOCKED',
    dependsOn: [33],
    unlocks: [35],
    guidanceEn: 'Run Aura AI Final Decision Review to inspect strengths, concerns, and recommendations. Mohannad retains final decision authority.',
    guidanceAr: 'شغل استشارة الذكاء الاصطناعي لتأكيد السلامة ومراجعة المخاطر. القرار النهائي يظل بيد القائد مهند.',
    aiTool: '🤖 Aura AI Competition Analyst',
    aiPrompt: 'Run final submission review on chosen candidate model, CV history, LB score, blockers log, and Red Team clearances.',
    requiredOutput: 'Aura AI Final Submission Intelligence Report.',
    handoffMessageEn: '🟢 Aura AI completed final decision analysis. Mohannad can generate final submission file.',
    handoffMessageAr: '🟢 أكمل الذكاء الاصطناعي تحليل القرار النهائي. يمكن لمهند توليد ملف التسليم.',
    recipient: 'mohannad'
  },

  // --- PHASE 12 ---
  {
    id: 35,
    phase: 'PHASE_12',
    order: 35,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '📦 Generate Versioned Final Submission File',
    titleAr: '📦 توليد ملف التسليم النهائي المسمّى بإصداره',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [34],
    unlocks: [36],
    guidanceEn: 'Generate versioned submission file (e.g. submission_final_EXP024.csv). Never name it generic final.csv!',
    guidanceAr: 'أنشئ ملف التسليم المسمى بإصداره (مثل submission_final_EXP024.csv). لا تسمّه final.csv أبداً!',
    aiTool: '💻 Codex',
    aiPrompt: `Write Python script to save test predictions to versioned submission CSV file formatted with date, model name, and local CV score.`,
    requiredOutput: 'submission_final_EXP024.csv generated.',
    handoffMessageEn: '🔔 Mohannad generated final submission file. Dyaa must perform Final Submission QA.',
    handoffMessageAr: '🔔 أنشأ مهند ملف التسليم النهائي. يجب على ضياء إجراء الفحص النهائي.',
    recipient: 'dyaa'
  },
  {
    id: 36,
    phase: 'PHASE_12',
    order: 36,
    owner: 'dyaa',
    ownerRole: '🛡️ Dyaa (Red Team QA)',
    titleEn: '🛡️ FINAL SUBMISSION QA (Blocking Gate)',
    titleAr: '🛡️ الفحص والاعتماد النهائي القاطع (Blocking Gate)',
    type: 'blocking',
    status: 'LOCKED',
    dependsOn: [35],
    unlocks: [37],
    guidanceEn: 'THIS IS A BLOCKING GATE. Check 15 verification items: exact row count, non-null values, correct IDs, prediction range, column order, valid format.',
    guidanceAr: 'هذه بوابة فحص قاطعة! افحص البنود الـ 15: الصفوف، عدم وجود NaN، صحة المعرفات، ونطاق التوقعات.',
    aiTool: '🟠 Claude / 💻 Codex',
    aiPrompt: `Perform exhaustive programmatic verification of final submission file against sample_submission.csv: exact row count, zero NaNs, exact column header match.`,
    requiredOutput: '🛡️ FINAL SUBMISSION CLEARED (Signed by Dyaa).',
    handoffMessageEn: '🟢 SUBMISSION CLEARED! Dyaa approved the final file. Mohannad can proceed with final upload.',
    handoffMessageAr: '🟢 تم اعتماد التسليم النهائي! وافق ضياء على الملف النهائي. يمكن لمهند رفع الملف الآن.',
    recipient: 'mohannad'
  },
  {
    id: 37,
    phase: 'PHASE_12',
    order: 37,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '🏆 Final Upload to Platform (Kaggle / IEEE)',
    titleAr: '🏆 الرفع الرسمي للملف على منصة المسابقة',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [36],
    unlocks: [38],
    guidanceEn: 'Show dramatic final submission screen. Confirm selected file checkbox and click 🚀 SUBMIT TO KAGGLE.',
    guidanceAr: 'افتح شاشة التسليم النهائي الدراماتيكية. تأكد من تحديد الملف واضغط زر 🚀 رفع التسليم النهائي للمنافسة.',
    aiTool: '🧠 ChatGPT',
    aiPrompt: 'Review final upload checklist, log submission timestamp, and confirm team submission completion.',
    requiredOutput: 'Final Submission Uploaded.',
    handoffMessageEn: '🔔 Mohannad uploaded final submission file.',
    handoffMessageAr: '🔔 رفع مهند ملف التسليم النهائي على المنصة.',
    recipient: 'all'
  },
  {
    id: 38,
    phase: 'PHASE_12',
    order: 38,
    owner: 'mohannad',
    ownerRole: '👑 Mohannad (Team Leader)',
    titleEn: '✅ Record Final Leaderboard Result & Complete Mission',
    titleAr: '✅ تسجيل النتيجة النهائية واختتام غرفة العمليات',
    type: 'sequential',
    status: 'LOCKED',
    dependsOn: [37],
    unlocks: [],
    guidanceEn: 'Record final Public Leaderboard score, submission timestamp, and final rank. Celebrate completion!',
    guidanceAr: 'أدخل نتيجة لوحة الصدارة النهائية، التوقيت، والترتيب الحالي. مبروك إكمال المسابقة بنجاح!',
    aiTool: '🤖 Aura AI Analyst',
    aiPrompt: 'Summarize team performance across all 38 steps, compute final speed efficiency, and generate competition recap report.',
    requiredOutput: '🎉 COMPETITION PIPELINE COMPLETE!',
    handoffMessageEn: '🎉 COMPETITION PIPELINE COMPLETE! NextAura AI War Room mission accomplished.',
    handoffMessageAr: '🎉 اكتمل بروتوكول المسابقة بنجاح! مبروك لفريق NextAura AI.',
    recipient: 'all'
  }
];
